server:
  port: 8022
spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: 192.168.136.128
    port: 5673
    username: admin
    password: admin

mq:
  consumer:
    queue: MyQueue
    exchange: MyExchange
    routing: MyRouting