server:
  port: 8021
spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 192.168.136.128
    port: 5673
    username: admin
    password: admin
mq:
  provider:
    routing: MyRouting
    queue: MyQueue
    exchange: MyExchange